version: '3.7'
services:
  Service_1:
    image: service_1
    build: ./Service_1
    ports:
    - target: 5000
      published: 5000
      protocol: tcp

    environment:
        FULLNAME_DB_URI: ${FULLNAME_DB_URI}
        SECRET_KEY: ${SECRET_KEY}
    depends_on:
      - Service_4
      
  Service_2:
    image: service_2
    build: ./Service_2
    ports:
    - target: 5000
      published: 5001
      protocol: tcp
  Service_3:
    image: service_3
    build: ./Service_3
    ports:
    - target: 5000
      published: 5002
      protocol: tcp
  Service_4:
    image: service_4
    build: ./Service_4
    ports:
    - target: 5000
      published: 5003
      protocol: tcp
    depends_on:
      - Service_2 
      - Service_3

    
