version: '3.7'
services:
  Service_1:
    image: emmanuelagyapong/service_1
    
    ports:
    - target: 5000
      published: 5000
      protocol: tcp
    networks:
      - ingress
    deploy:
      replicas: 1
    environment:
        FULLNAME_DB_URI: ${FULLNAME_DB_URI}
        SECRET_KEY: ${SECRET_KEY}
    depends_on:
      - Service_4
      
  Service_2:
    image: emmanuelagyapong/service_2
    networks:
      - ingress
    deploy:
      replicas: 1
    ports:
    - target: 5000
      published: 5001
      protocol: tcp
  Service_3:
    image: emmanuelagyapong/service_3
    networks:
      - ingress
    deploy:
      replicas: 1
    ports:
    - target: 5000
      published: 5002
      protocol: tcp
  Service_4:
    image: emmanuelagyapong/service_4
    networks:
      - ingress
    deploy:
      replicas: 1
    ports:
    - target: 5000
      published: 5003
      protocol: tcp
    depends_on:
      - Service_2 
      - Service_3

networks:
  ingress:
      driver: overlay

    
