- name: install docker
  hosts: master
  become: true
  roles:
    - docker-installation

- name: initialise docker swarm
  hosts: master
  become: true
  roles:
    - docker-swarm-init

- name: add workers to the swarm
  hosts: workers
  become: true
  roles:
    - docker-swarm-add-workers
